### ISSUE TITLE
Consolidate file paths for code generation

### ISSUE THREAD

**Issue by nikolasburk** [graphql-nexus/nexus-plugin-prisma#251]
When using Prisma with `nexus-prisma`, codegen is typically configured in prisma.yml. This is an [example](https://github.com/prisma/prisma-examples/blob/master/typescript/graphql/prisma/prisma.yml#L7-L16) from the TypeScript GraphQL examples from the `prisma-examples` repo:

```
generate:
  - generator: typescript-client
    output: ../src/generated/prisma-client/

hooks:
  post-deploy:
    - npx nexus-prisma-generate --client ./src/generated/prisma-client --output ./src/generated/nexus-
```

Notice that:

- For the Prisma client, I need to use `..` to navigate to the parent directory first to get to `src`
- For `nexus-prisma` typings, I can just navigate to `src` from the current directory

I find this a bit confusing. Is it possible to consolidate this?>

**Comment by Weakky** [comment]
Fixed, will be release in next version. Careful however, that's a **breaking change**.

**Comment by sam-at-work** [comment]
this still doesn't seem to be fixed in 0.3.6
`nexus-prisma-generate` still seems to be using a path relative to the root of the project.

Also following the example in the file that was changed here: https://github.com/prisma/nexus-prisma/commit/01e24b4a4ad4e4be23e94d56f8b0bbd7c5570eea
I get an error if I don't include `npx` at the start of the command.

**Comment by Weakky** [comment]
It does work properly for me locally, not sure what's your local setup

The example has nexus-prisma-generate in devDependencies hence why it doesn't use npx

**Comment by sam-at-work** [comment]
Hi Weakky, thanks for the quick response. 

I don't have `nexus-prisma-generate` at all in my `package.json` file. I just assumed it was part of `nexus-prisma`.

Is it something I should be explicitly adding? (also wondering if that could be part of the issue for me)

The example projects in https://github.com/prisma/prisma-examples don't seem to have it in `package.json` either.

**Comment by sam-at-work** [comment]
Here is my current setup

package.json
```
{
  "dependencies": {
    ...
    "nexus": "0.11.6",
    "nexus-prisma": "0.3.6",
    "prisma-client-lib": "1.31.1",
  },
  "devDependencies": {
    ...
    "nexus-prisma-generate": "^0.3.6",
  },
...
}
```

prisma.yml
```
# Defines your models, each model is mapped to the database as a table.
datamodel: datamodel.prisma
endpoint: http://xxxxxxx

# Specifies the language and directory for the generated Prisma client.
generate:
  - generator: typescript-client
    output: ../src/generated/prisma-client
  - generator: graphql-schema
    output: ./generated/prisma.graphql

# Seed your service with initial data based on `seed.graphql`.
seed:
#  import: seed.graphql
  run: ts-node prisma/seed.ts

# Ensures Prisma client is re-generated after a datamodel change.
hooks:
  post-deploy:
    - nexus-prisma-generate --output ./src/generated/nexus-prisma
```
The above setup works correctly.

When i change the post deploy hook to:
`nexus-prisma-generate --output="../src/generated/nexus-prisma"`
the output ends up in the following path from the root of my project `"../src/generated/nexus-prisma` (yes the first folder is actually called `"..`)

If I change the line to:
`- nexus-prisma-generate --output=../src/generated/nexus-prisma`
the output ends up in a `src` folder in the folder one level up from the root of my project.
