### ISSUE TITLE
Cannot return null for non-nullable field (nexus-prisma)

### ISSUE THREAD

**Issue by faileon** [graphql-nexus/nexus-plugin-prisma#289]
Nested **@embedded** relation returns null from nexus-prisma, while prisma-client works fine.

I have a simple data model:
```graphql
type Polozka{
  id: ID! @id,
  nazev: [Preklad!]!,
  mnozstvi: Float!,
  cena: Float!,
  createdAt: DateTime! @createdAt,
  updatedAt: DateTime! @updatedAt
}

type Preklad @embedded{
  jazyk: Jazyk!,
  text: String!,
}

type Jazyk{
  id: ID! @id,
  nazev: String! @unique,
  kod: String! @unique,
  createdAt: DateTime! @createdAt
}
```

**Description**
Two identical queries:
```graphql
query{
  polozkas{
    id
    nazev{
      text
      jazyk{
        id
        nazev
        kod
      }
    }
  }
}
```
Return different results. Prisma client returns correctly all nested relations, but nexus-prisma returns null on the nested **jazyk** relation. I checked the mongodb in the docker and the database is correct with all the relations etc. It seems that nexus-prisma can't handle an embedded relation, which has a link relation. Implementation of nexus-prisma server code was done by following the official tutorial and github examples, everything is exposed, etc.

I expose the queries as following, I also tried to modify the resolver and see what's happening:
```javascript
    t.prismaFields(['polozkas'])
    /*t.field('polozkas',{
      type: 'Polozka',
      list: true,
      resolve: async(parent: any, object: any, ctx: Context, info: GraphQLResolveInfo) => {
        console.log(info);
        return await ctx.prisma.polozkas({}).then(polozky => {
          polozky.forEach((element: any) => {
            console.log(element) //the jazyk relation is undefined here
          });
          return polozky;
        })
      }
    })*/
```

**Screenshots**

![chrome_2019-06-05_10-46-18](https://user-images.githubusercontent.com/9354213/58943893-00796f00-8781-11e9-8c67-5c195718e488.png)

**Comment by Weakky** [comment]
Hey there 👋, are you using mongo?

If so, try adding `databaseType: document` to your `prisma.yml` file

**Comment by faileon** [comment]
I do have `databaseType: document`

My `prisma.yml:`
```yaml
endpoint: http://192.168.99.100:4466
datamodel: datamodel.prisma
databaseType: document
hooks:
  post-deploy:
    - prisma generate
    - npx nexus-prisma-generate --client ./generated/prisma-client --output ./generated/nexus-prisma

generate:
  - generator: typescript-client
    output: ../src/generated/prisma-client/
```

Forgot the version details, so here we go:

**Versions:**
 - Connector: MongoDB
 - Prisma Server: 1.34.0
 - prisma CLI: prisma/1.34.0, node-v10.15.1
 - OS: Windows 10
 - other dependencies: nexus-prisma 0.3.7, nexus 0.11.7, graphql-yoga 1.17.4

I found a very similar issue to mine, maybe it's related?
https://github.com/prisma/prisma/issues/4443
(I also included a simplifed example of my problem in that thread)
